[package]
name = "widgetry"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[features]
native-backend = ["clipboard", "glutin", "tokio"]
wasm-backend = ["instant/wasm-bindgen", "js-sys", "wasm-bindgen", "wasm-bindgen-futures", "wasm-streams", "web-sys"]

[dependencies]
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = { workspace = true }
# backtrace = "0.3.40"
clipboard = { version = "0.5.0", optional = true }
colorous = { workspace = true }
downcast-rs = "1.2.0"
flate2 = { workspace = true }
fs-err = { workspace = true }
futures = { workspace = true }
futures-channel = { workspace = true }
geojson = { workspace = true }
geom = { workspace = true }
glow = "0.12.1"
glutin = { git = "https://github.com/rust-windowing/glutin", optional = true, rev = "2bffbf52d6b4f4c32adc463818e10ac8082948e4" }
htmlescape = "0.3.1"
image = { version = "0.24.6", default-features = false, features=["gif", "png"] }
instant = { workspace = true }
js-sys = { version = "0.3.47", optional = true }
log = { workspace = true }
lru = "0.10.0"
lyon = "1.0.0"
serde = { workspace = true }
serde_json = { workspace = true }
taffy = "0.2.2"
tokio = { workspace = true, optional = true }
ttf-parser = "0.19.0"
usvg = "0.32.0"
usvg-text-layout = { version = "0.32.0", default-features = false }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { version = "0.4.34", optional = true }
wasm-streams = { version = "0.3.0", optional = true }
webbrowser = "0.8.9"
winit = "0.27.0"

[dependencies.web-sys]
workspace = true
optional = true
# TODO Some of these may only be needed in map_gui. It's hard to detangle.
features = [
  "Headers",
  "History",
  "ReadableStream",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Window",
]
