[package]
name = "collisions"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[dependencies]
geom = { workspace = true }
kml = { path = "../kml" }
log = { workspace = true }
serde = { workspace = true }
