[package]
name = "parking_mapper"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[features]
default = ["map_gui/native", "reqwest", "widgetry/native-backend"]

[dependencies]
abstio = { path = "../../abstio" }
abstutil = { path = "../../abstutil" }
anyhow = { workspace = true }
fs-err = { workspace = true }
geom = { workspace = true }
log = { workspace = true }
map_gui = { path = "../../map_gui" }
map_model = { path = "../../map_model" }
reqwest = { version = "0.11.17", optional = true, default-features=false, features=["blocking", "rustls-tls"] }
structopt = { workspace = true }
widgetry = { path = "../../widgetry" }
xmltree = "0.10.1"
