[package]
name = "ltn"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["home", "map_gui/native", "widgetry/native-backend"]
wasm = ["getrandom/js", "map_gui/wasm", "wasm-bindgen", "widgetry/wasm-backend"]

[dependencies]
abstio = { path = "../../abstio" }
abstutil = { path = "../../abstutil" }
anyhow = { workspace = true }
blockfinding = { path = "../../blockfinding" }
contour = { workspace = true }
csv = { workspace = true }
flate2 = { workspace = true }
futures-channel = { workspace = true }
geo = { workspace = true }
geojson = { workspace = true }
geom = { workspace = true }
getrandom = { workspace = true, optional = true }
home = { version = "0.5.5", optional = true }
lazy_static = "1.4.0"
log = { workspace = true }
maplit = "1.0.2"
map_gui = { path = "../../map_gui" }
map_model = { path = "../../map_model" }
md5 = "0.7.0"
rand = { workspace = true }
rand_xorshift = { workspace = true }
regex = "1.8.1"
serde = { workspace = true }
serde_json = { workspace = true }
osm2streets = { git = "https://github.com/a-b-street/osm2streets" }
synthpop = { path = "../../synthpop" }
wasm-bindgen = { workspace = true, optional = true }
widgetry = { path = "../../widgetry" }
structopt = { workspace = true }

[dev-dependencies]
tests = { path = "../../tests" }
fs-err = { workspace = true }
