[package]
name = "widgetry_demo"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["widgetry/native-backend"]
wasm = ["getrandom/js", "wasm-bindgen", "widgetry/wasm-backend"]

[dependencies]
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
geom = { workspace = true }
getrandom = { workspace = true, optional = true }
log = { workspace = true }
rand = { workspace = true }
rand_xorshift = { workspace = true }
svg_face = "0.1.3"
wasm-bindgen = { workspace = true, optional = true }
widgetry = { path = "../widgetry" }
