[package]
name = "santa"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["map_gui/native", "widgetry/native-backend"]
wasm = ["getrandom/js", "map_gui/wasm", "wasm-bindgen", "widgetry/wasm-backend"]

[dependencies]
abstio = { path = "../../abstio" }
abstutil = { path = "../../abstutil" }
anyhow = { workspace = true }
geom = { workspace = true }
getrandom = { workspace = true, optional = true }
kml = { path = "../../kml" }
log = { workspace = true }
map_gui = { path = "../../map_gui" }
map_model = { path = "../../map_model" }
rand = { workspace = true }
rand_xorshift = { workspace = true }
rodio = { version = "0.17.3", default-features = false, features = ["vorbis"] }
serde = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
widgetry = { path = "../../widgetry" }
